name: "test-and-initial-gh-page"
on:
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node_version:
                    - 18
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
            - name: Installing dependencies
              run: yarn
            - name: Running tests
              run: yarn test
    initiate-gh-pages:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 18
              uses: actions/setup-node@v2
              with:
                  node-version: "18"
            - name: Installing dependencies
              run: yarn
            - name: Initiating GitHub Pages
              run: |
                  git config --global user.email ${{ secrets.EMAIL }}
                  git config --global user.name ${{ secrets.USERNAME }}
                  git remote set-url origin https://${{ secrets.PERSONAL_AC }}@github.com/${{ secrets.USERNAME }}/${{ secrets.REPO }}.git
                  yarn run deploy
